version: 0.0
os: linux
files:
  - source: /
    destination: /home/magento
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
    - location: scripts/change_permissions
      timeout: 300
      runas: root
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

